name: 'build'

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: construct release tagging
        run: |
          IMAGE_TAG="ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest"
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          echo "building ${IMAGE_TAG}"
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
      - uses: docker/setup-buildx-action@v2
      - name: build docker image
        run: |
          docker build --build-arg "GITHUB_TOKEN=${{ secrets.PAT }}" . -t "${IMAGE_TAG}"
          docker push "${IMAGE_TAG}"
